<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    use HasFactory;

    protected $casts = [
        'released_at' => 'datetime',
    ];

    protected static function booted()
    {
        static::creating(fn(Course $course) => $course->slug = \Str::slug($course->title));

        parent::booted(); // TODO: Change the autogenerated stub
    }

    public function scopeReleased(Builder $builder): Builder
    {
        return $builder->whereNotNull('released_at');
    }
}
