<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Course extends Model
{
    use HasFactory;

    protected $casts = [
        'released_at' => 'datetime',
        'learning' => 'array'
    ];

    protected static function booted()
    {
        static::creating(fn(Course $course) => $course->slug = \Str::slug($course->title));

        parent::booted(); // TODO: Change the autogenerated stub
    }

    public function scopeReleased(Builder $builder): Builder
    {
        return $builder->whereNotNull('released_at');
    }

    /**
     * @return HasMany<Course>
     */
    public function videos(): HasMany
    {
        return $this->hasMany(Video::class);
    }

    public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'purchased_course')->withTimestamps();
    }
}
