<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    use HasFactory;

    protected static function booted()
    {
        static::creating(fn(Video $video) => $video->slug = \Str::slug($video->title));

        parent::booted(); // TODO: Change the autogenerated stub
    }
}
